#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480

#define WIFI_SSID "YOUR_WIFI"
#define WIFI_PASS "YOUR_PASSWORD"
#define API_URL   "http://YOUR_SERVER"

#define CLOCK_UPDATE_INTERVAL 600000
#define WEATHER_UPDATE_INTERVAL 3600000

